services:
  minio:
    image: quay.io/minio/minio
    container_name: djangominio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./dockerdata/minio:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminadmin
    command: server /data --console-address ":9001"