# Generated by Django 5.1 on 2024-08-28 09:10

import django_minio_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.FileField(storage=django_minio_backend.models.MinioBackend(bucket_name='videoshotsdjango'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='Bild')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField(max_length=300)),
                ('publication_date', models.DateField()),
            ],
        ),
    ]
