# Generated by Django 5.1 on 2024-08-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='publication_date',
            field=models.DateField(default='2024-13-28'),
        ),
    ]
