# Generated by Django 3.2.4 on 2024-09-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0002_alter_screenshot_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='publication_date',
            field=models.DateField(default='2024-18-15'),
        ),
    ]
